[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/ArduinoGraphics@^1.1.2
    jandrassy/ArduinoOTA@^1.1.1

[env:ota]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/ArduinoGraphics@^1.1.2
    jandrassy/ArduinoOTA@^1.1.1
upload_protocol = custom
upload_port = 192.168.1.102
upload_command = curl -u arduino:arduino --data-binary @$SOURCE http://$UPLOAD_PORT:65280/sketch
