// Generated by protocol/generate_protocol.py from protocol/schema.json. DO NOT EDIT.
#pragma once
#include <stdint.h>

// Faults
#define FAULT_NONE                           0x00
#define FAULT_IMU_ERROR                      0x01
#define FAULT_HIP_INIT_TIMEOUT               0x02
#define FAULT_HIP_FEEDBACK_LOST              0x03
#define FAULT_HIP_LARGE_POS_CMD              0x04
#define FAULT_CALIBRATION_TIMEOUT            0x05
#define FAULT_HUMAN_ESTOP                    0x06
#define FAULT_PITCH_WATCHDOG                 0x08
#define FAULT_WHEEL_RUNAWAY                  0x09
#define FAULT_IMU_LOST                       0x0A
#define FAULT_WHEEL_FEEDBACK_LOST            0x0B
#define FAULT_WHEEL_INIT_TIMEOUT             0x0C
#define FAULT_STANDUP_FAILED                 0x0D

// Commands
#define CMD_ID_SET_MODE                      0x01
#define CMD_ID_PING                          0x02
#define CMD_ID_HIP                           0x05
#define CMD_ID_REBOOT                        0x06
#define CMD_ID_WHEEL                         0x07
#define CMD_ID_SET_TELEM_TRANSPORT           0x08
#define CMD_ID_PARAM_SET                     0x10
#define CMD_ID_PARAM_GET                     0x11
#define CMD_ID_LOG                           0x12
#define CMD_ID_PARAM_RESET_DEFAULTS          0x13
#define CMD_ID_TEST_INJECT_CORRUPT           0x14
