-- GENERATED by radio/tools/gen_robotdef_lua.py -- DO NOT EDIT BY HAND.
-- Source: firmware/robot_teensy/protocol/schema.json
--         firmware/robot_teensy/shared/comm_protocol.h  (fault_severity)
--         firmware/robot_teensy/esp32/src/main.cpp      (mode_color)
-- Regenerate after any schema change; --check catches staleness in CI.

local M = {}

-- Robot states, keyed by the wire value of TelemetryPayload.robot_state.
-- colour is 0xRRGGBB and matches the ESP32 TFT / Neopixel table exactly,
-- so radio, robot lights and GUI never disagree about what state means.
M.states = {
  [0] = { name="STARTUP", short="STARTUP", colour=0xFFFFFF, wav="st_boot" },
  [1] = { name="CALIBRATION", short="CALIB", colour=0x0000FF, wav="st_calib" },
  [2] = { name="STANDBY", short="STANDBY", colour=0xFFFF00, wav="st_stby" },
  [3] = { name="RUNNING", short="RUNNING", colour=0x00FF00, wav="st_run" },
  [4] = { name="ESTOP", short="ESTOP", colour=0xFF0000, wav="st_estop" },
  [5] = { name="MANUAL", short="MANUAL", colour=0x00FFFF, wav="st_man" },
  [6] = { name="CMD_REJECT", short="REJECT", colour=0xFF6400, wav="st_rej" },
  [7] = { name="JUMPING", short="JUMPING", colour=0xC800FF, wav="st_jump" },
  [8] = { name="STANDING_UP", short="STANDUP", colour=0xFF3C00, wav="st_up" },
  [9] = { name="DISARMING", short="DISARMING", colour=0xFFB400, wav="st_disar" },
}

-- Fault codes. tier drives how loudly the radio annunciates:
--   SOFT       single beep      -- ESTOP -> STANDBY, no re-init needed
--   REPOSITION two-tone + voice -- robot fell / calib failed; go pick it up
--   GUI_FIX    voice, no alarm  -- bad param, fix it before reset
--   REBOOT     siren + haptic   -- hardware dropout, power-cycle required
M.faults = {
  [0] = { name="NONE", tier="SOFT", wav=nil, desc="" },
  [1] = { name="IMU ERROR", tier="REBOOT", wav="f_imuerr",
        desc="IMU reported ERROR during startup" },
  [2] = { name="HIP INIT TIMEOUT", tier="REBOOT", wav="f_hipini",
        desc="no CAN reply from hip motors within 2 s of boot" },
  [3] = { name="HIP FEEDBACK LOST", tier="REBOOT", wav="f_hipfb",
        desc="hip CAN feedback timed out during operation" },
  [4] = { name="HIP POS JUMP", tier="GUI_FIX", wav="f_hipjmp",
        desc="commanded position jump exceeded MAX_HIP_DELTA_RAD" },
  [5] = { name="CALIB TIMEOUT", tier="REPOSITION", wav="f_calib",
        desc="retract-switch homing safety check failed" },
  [6] = { name="HUMAN ESTOP", tier="SOFT", wav="f_human",
        desc="ESTOP requested by user via GUI button or radio" },
  [8] = { name="PITCH WATCHDOG", tier="REPOSITION", wav="f_pitchw",
        desc="pitch outside [-pitch_wd_bwd, +pitch_wd_fwd] (asymmetric, gain-scheduled by leg height) for > 200 ms. Suppressed in STANDING_UP." },
  [9] = { name="WHEEL RUNAWAY", tier="SOFT", wav="f_runawy",
        desc="wheel velocity exceeded 2x soft governor limit" },
  [10] = { name="IMU LOST", tier="REBOOT", wav="f_imulos",
        desc="IMU left NOMINAL while RUNNING/JUMPING (silence or heavy loss)" },
  [11] = { name="WHEEL FEEDBACK LOST", tier="REBOOT", wav="f_whlfb",
        desc="wheel encoder timeout or ODrive error during operation" },
  [12] = { name="WHEEL INIT TIMEOUT", tier="REBOOT", wav="f_whlini",
        desc="no CAN reply from wheel motors within 2 s of boot" },
  [13] = { name="STANDUP FAILED", tier="REPOSITION", wav="f_stndup",
        desc="standup denied (pitch out of recoverable range) or exhausted retries/diverged" },
  [14] = { name="ROLL WATCHDOG", tier="REPOSITION", wav="f_rollw",
        desc="|roll| > roll_watchdog_limit for > 200 ms (lateral tip guard)" },
  [15] = { name="JUMP TIMEOUT", tier="REPOSITION", wav="f_jumpto",
        desc="jump landing or handoff was not captured before its live phase timeout, or the complete jump exceeded its computed phase budget" },
}

-- Reverse maps for the CRSF FLIGHT_MODE text sensor. State and fault
-- reach the radio twice: as numbers in the private 0x24 frame, and as
-- text here. The text is the half guaranteed to relay through ELRS, so
-- these let the HUD and the annunciator keep working on it alone.
M.fmState = {
  ["STARTUP"] = 0,
  ["CALIBRATION"] = 1,
  ["STANDBY"] = 2,
  ["RUNNING"] = 3,
  ["ESTOP"] = 4,
  ["MANUAL"] = 5,
  ["CMD_REJECT"] = 6,
  ["JUMPING"] = 7,
  ["STANDING_UP"] = 8,
  ["DISARMING"] = 9,
}

M.fmFault = {
  ["IMUERR"] = 1,
  ["HIPINIT"] = 2,
  ["HIPFB"] = 3,
  ["HIPJUMP"] = 4,
  ["CALTIME"] = 5,
  ["HUMAN"] = 6,
  ["PITCHWD"] = 8,
  ["RUNAWAY"] = 9,
  ["IMULOST"] = 10,
  ["WHLFB"] = 11,
  ["WHLINIT"] = 12,
  ["STANDUP"] = 13,
  ["ROLLWD"] = 14,
  ["JUMPTO"] = 15,
}

M.jumpPhase    = { "CROUCH", "EXTEND", "RETRACT", "LANDING", "HANDOFF" }
M.standupPhase = { "CROUCH", "RECOVER", "PAUSE", "STIFFEN" }

-- health_flags bits, comm_protocol.h HEALTH_*
M.health = {
  HIP_L_OK = { bit=1, label="hip L" },
  HIP_R_OK = { bit=2, label="hip R" },
  WM_L_OK = { bit=4, label="whl L" },
  WM_R_OK = { bit=8, label="whl R" },
  HIP_LIMITS_VALID = { bit=16, label="limits" },
  IMU_NOMINAL = { bit=32, label="IMU" },
  LQR_ACTIVE = { bit=64, label="LQR" },
  VEL_PI_SAT = { bit=128, label="velSat" },
  YAW_PI_SAT = { bit=256, label="yawSat" },
  WM_L_VEL_LIMITED = { bit=512, label="govL" },
  WM_R_VEL_LIMITED = { bit=1024, label="govR" },
  LOOP_OVERRUN = { bit=2048, label="overrun" },
}

function M.state(id)
  return M.states[id] or { name="?", short="?", colour=0x808080, wav=nil }
end

function M.fault(code)
  return M.faults[code] or
         { name=string.format("FAULT %d", code), tier="REBOOT", wav=nil, desc="" }
end

return M
