// Generated by protocol/generate_protocol.py from protocol/schema.json. DO NOT EDIT.
#pragma once
#include <stdint.h>

// Human-readable names for the CRSF FLIGHT_MODE telemetry frame.
// Kept to 13 characters so EdgeTX does not truncate them.

static const char* const STATE_NAMES[10] = {
    /*  0 */ "STARTUP",
    /*  1 */ "CALIBRATION",
    /*  2 */ "STANDBY",
    /*  3 */ "RUNNING",
    /*  4 */ "ESTOP",
    /*  5 */ "MANUAL",
    /*  6 */ "CMD_REJECT",
    /*  7 */ "JUMPING",
    /*  8 */ "STANDING_UP",
    /*  9 */ "DISARMING",
};

// Short fault names. Prefixed with '!' by the caller so a fault is
// unmistakable on the radio's FM field at a glance.
static const char* const FAULT_SHORT_NAMES[16] = {
    /*  0 */ "OK",
    /*  1 */ "IMUERR",
    /*  2 */ "HIPINIT",
    /*  3 */ "HIPFB",
    /*  4 */ "HIPJUMP",
    /*  5 */ "CALTIME",
    /*  6 */ "HUMAN",
    /*  7 */ "?",
    /*  8 */ "PITCHWD",
    /*  9 */ "RUNAWAY",
    /* 10 */ "IMULOST",
    /* 11 */ "WHLFB",
    /* 12 */ "WHLINIT",
    /* 13 */ "STANDUP",
    /* 14 */ "ROLLWD",
    /* 15 */ "JUMPTO",
};
