// Generated by protocol/generate_protocol.py from protocol/schema.json. DO NOT EDIT.
#pragma once
#include <stdint.h>

typedef enum : uint8_t {
    STATE_STARTUP            = 0,
    STATE_CALIBRATION        = 1,
    STATE_STANDBY            = 2,
    STATE_RUNNING            = 3,
    STATE_ESTOP              = 4,
    STATE_MANUAL             = 5,
    STATE_CMD_REJECT         = 6,
    STATE_JUMPING            = 7,
    STATE_STANDING_UP        = 8,
    STATE_DISARMING          = 9,
} RobotStateEnum;
