[platformio]
default_envs = esp32dev

[env:esp32dev]
platform         = espressif32@7.0.0
board            = esp32dev
framework        = arduino
build_flags =
    -I"../shared" -Isrc
    -DUSER_SETUP_LOADED
    -DST7789_DRIVER
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=2
    -DTFT_RST=4
    -DTFT_BL=15
    -DSPI_FREQUENCY=80000000
    -DSPI_READ_FREQUENCY=6000000
    -DLOAD_GLCD
    -DTFT_RGB_ORDER=0
build_src_filter = +<*> -<vl53l1x/> -<neopixel/> -<tft_benchmark/>
lib_extra_dirs   = ../shared
lib_deps         =
    bodmer/TFT_eSPI
    fastled/FastLED
    pololu/VL53L1X
monitor_filters  = esp32_exception_decoder

[env:neopixel_demo]
platform         = espressif32
board            = esp32dev
framework        = arduino
build_src_filter = -<*> +<neopixel/>
lib_deps         =
    fastled/FastLED

[env:vl53l1x_demo]
platform         = espressif32
board            = esp32dev
framework        = arduino
build_src_filter = -<*> +<vl53l1x/>
lib_deps         =
    pololu/VL53L1X

[env:tft_benchmark]
platform         = espressif32
board            = esp32dev
framework        = arduino
build_flags      =
    -DUSER_SETUP_LOADED
    -DST7789_DRIVER
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=2
    -DTFT_RST=4
    -DTFT_BL=15
    -DSPI_FREQUENCY=80000000
    -DSPI_READ_FREQUENCY=6000000
    -DLOAD_GLCD
    -DTFT_RGB_ORDER=0
build_src_filter = -<*> +<tft_benchmark/>
lib_deps         =
    bodmer/TFT_eSPI

[env:test_esp32]
extends     = env:esp32dev
build_src_filter = -<src/>
test_filter = test_*

[env:native]
platform    = native
build_flags = -I"../shared"
test_filter = test_telemetry
