[platformio]
default_envs = esp32dev

[env:esp32dev]
platform         = espressif32
board            = esp32dev
framework        = arduino
build_flags      = -I"../shared" -Isrc
build_src_filter = +<*> -<vl53l1x/> -<neopixel/>
lib_extra_dirs   = ../shared
lib_deps         =
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GFX Library
    fastled/FastLED

[env:neopixel_demo]
platform         = espressif32
board            = esp32dev
framework        = arduino
build_src_filter = -<*> +<neopixel/>
lib_deps         =
    fastled/FastLED

[env:vl53l1x_demo]
platform         = espressif32
board            = esp32dev
framework        = arduino
build_src_filter = -<*> +<vl53l1x/>
lib_deps         =
    pololu/VL53L1X

[env:test_esp32]
extends     = env:esp32dev
build_src_filter = -<src/>
test_filter = test_*

[env:native]
platform    = native
build_flags = -I"../shared"
test_filter = test_telemetry
